apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: mern-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: YOUR_DOCKERHUB/backend:latest

          ports:
            - containerPort: 5000

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mern-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mern-secret
                  key: JWT_SECRET